config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :concertevents
  root to: redirect('/concertevents')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concertevent.rb
class Concertevent < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/concertevents_controller.rb
class ConcerteventsController < ApplicationController
  before_action :set_concertevent, only: [:show, :edit, :update, :destroy]

  # GET /concertevents
  # GET /concertevents.json
  def index
    @concertevents = Concertevent.all
  end

  # GET /concertevents/1
  # GET /concertevents/1.json
  def show
  end

  # GET /concertevents/new
  def new
    @concertevent = Concertevent.new
  end

  # GET /concertevents/1/edit
  def edit
  end

  # POST /concertevents
  # POST /concertevents.json
  def create
    @concertevent = Concertevent.new(concertevent_params)

    respond_to do |format|
      if @concertevent.save
        format.html { redirect_to @concertevent, notice: 'Concertevent was successfully created.' }
        format.json { render :show, status: :created, location: @concertevent }
      else
        format.html { render :new }
        format.json { render json: @concertevent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concertevents/1
  # PATCH/PUT /concertevents/1.json
  def update
    respond_to do |format|
      if @concertevent.update(concertevent_params)
        format.html { redirect_to @concertevent, notice: 'Concertevent was successfully updated.' }
        format.json { render :show, status: :ok, location: @concertevent }
      else
        format.html { render :edit }
        format.json { render json: @concertevent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concertevents/1
  # DELETE /concertevents/1.json
  def destroy
    @concertevent.destroy
    respond_to do |format|
      format.html { redirect_to concertevents_url, notice: 'Concertevent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concertevent
      @concertevent = Concertevent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concertevent_params
      params.require(:concertevent).permit(:name, :member, :datetime, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concertevents_helper.rb
module ConcerteventsHelper
end

app/views/concertevents/_form.html.erb
<%= form_with(model: concertevent, local: true) do |form| %>
  <% if concertevent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concertevent.errors.count, "error") %> prohibited this concertevent from being saved:</h2>

      <ul>
      <% concertevent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :member %>
    <%= form.number_field :member %>
  </div>

  <div class="field">
    <%= form.label :datetime %>
    <%= form.datetime_select :datetime %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concertevents/edit.html.erb
<h1>Editing Concertevent</h1>

<%= render 'form', concertevent: @concertevent %>

<%= link_to 'Show', @concertevent %> |
<%= link_to 'Back', concertevents_path %>

app/views/concertevents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concertevents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Member</th>
      <th>Datetime</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concertevents.each do |concertevent| %>
      <tr>
        <td><%= concertevent.name %></td>
        <td><%= concertevent.member %></td>
        <td><%= concertevent.datetime %></td>
        <td><%= concertevent.description %></td>
        <td><%= link_to 'Show', concertevent %></td>
        <td><%= link_to 'Edit', edit_concertevent_path(concertevent) %></td>
        <td><%= link_to 'Destroy', concertevent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concertevent', new_concertevent_path %>

app/views/concertevents/new.html.erb
<h1>New Concertevent</h1>

<%= render 'form', concertevent: @concertevent %>

<%= link_to 'Back', concertevents_path %>

app/views/concertevents/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @concertevent.name %>
</p>

<p>
  <strong>Member:</strong>
  <%= @concertevent.member %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @concertevent.datetime %>
</p>

<p>
  <strong>Description:</strong>
  <%= @concertevent.description %>
</p>

<%= link_to 'Edit', edit_concertevent_path(@concertevent) %> |
<%= link_to 'Back', concertevents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tests</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    
    
<p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, class: 'navbar-link'  %>
  <% end %>
</p>
    
    
    
    
    
    
    
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>